# permissions for end users to edit commonconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: commonconfig-editor-role
rules:
- apiGroups:
  - infrastructure.alauda.io
  resources:
  - commonconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - infrastructure.alauda.io
  resources:
  - commonconfigs/status
  verbs:
  - get
