# permissions for end users to view commonconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: commonconfig-viewer-role
rules:
- apiGroups:
  - infrastructure.alauda.io
  resources:
  - commonconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - infrastructure.alauda.io
  resources:
  - commonconfigs/status
  verbs:
  - get
